'use client'
import AuthProvider from "@/context/AuthProvider";
import "./globals.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <AuthProvider >
           {children}
        </AuthProvider>

      </body>
    </html>
  );
}
